/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import pack.control.controllerToko;
import pack.model.m_toko;

/**
 *
 * @author User
 */
public class home extends javax.swing.JFrame {
    controllerToko cToko;
    List<m_toko>listData = new ArrayList<>();
    /**
     * Creates new form home
     */
    
    
    public home(String user1) {
        initComponents();
        cToko = new controllerToko(this);
        cToko.isiTable();
        tfAdmin.setText(user1);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfAdmin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfKode = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        tfHarga = new javax.swing.JTextField();
        cbKategori = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbSimpan = new javax.swing.JButton();
        jbUbah = new javax.swing.JButton();
        jbBersihkan = new javax.swing.JButton();
        jbHapus = new javax.swing.JButton();
        jbKeluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbCari = new javax.swing.JComboBox<>();
        jbCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));
        jPanel1.setLayout(null);

        tfAdmin.setEditable(false);
        tfAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tfAdmin);
        tfAdmin.setBounds(130, 10, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Barang di Toko");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 40, 270, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Admin Toko :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 120);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Harga");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 220, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nama Barang");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 70, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kode Barang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 20, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jenis Packaging");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 170, 120, 30);
        jPanel2.add(tfKode);
        tfKode.setBounds(210, 20, 440, 30);
        jPanel2.add(tfNama);
        tfNama.setBounds(210, 70, 440, 30);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doz", "Lusinan", "Pack" }));
        jPanel2.add(cbJenis);
        cbJenis.setBounds(210, 170, 440, 30);
        jPanel2.add(tfHarga);
        tfHarga.setBounds(210, 220, 440, 30);

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Barang Lain", "Alat Tulis" }));
        jPanel2.add(cbKategori);
        cbKategori.setBounds(210, 120, 440, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Kategori Barang");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 120, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 120, 680, 300);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));
        jPanel3.setLayout(null);

        jbSimpan.setText("SIMPAN");
        jbSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(jbSimpan);
        jbSimpan.setBounds(40, 10, 130, 30);

        jbUbah.setText("UBAH");
        jbUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUbahActionPerformed(evt);
            }
        });
        jPanel3.add(jbUbah);
        jbUbah.setBounds(40, 70, 130, 30);

        jbBersihkan.setText("BERSIHKAN");
        jbBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBersihkanActionPerformed(evt);
            }
        });
        jPanel3.add(jbBersihkan);
        jbBersihkan.setBounds(40, 130, 130, 30);

        jbHapus.setText("HAPUS");
        jbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHapusActionPerformed(evt);
            }
        });
        jPanel3.add(jbHapus);
        jbHapus.setBounds(40, 190, 130, 30);

        jbKeluar.setText("KELUAR");
        jbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKeluarActionPerformed(evt);
            }
        });
        jPanel3.add(jbKeluar);
        jbKeluar.setBounds(40, 250, 130, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(690, 120, 210, 300);

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("cari berdasarkan kategori");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(0, 10, 210, 30);

        cbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "Makanan", "Barang Lain", "Alat Tulis" }));
        jPanel4.add(cbCari);
        cbCari.setBounds(30, 40, 150, 30);

        jbCari.setText("CARI");
        jbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCariActionPerformed(evt);
            }
        });
        jPanel4.add(jbCari);
        jbCari.setBounds(50, 80, 110, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(690, 430, 210, 160);

        tbBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "KodeBarang", "NamaBarang", "KategoriBarang", "JenisPackaging", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBarang);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 430, 670, 160);

        setSize(new java.awt.Dimension(915, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCariActionPerformed
        // TODO add your handling code here:
        cToko.CariKategori();
    }//GEN-LAST:event_jbCariActionPerformed

    private void jbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimpanActionPerformed
        // TODO add your handling code here:
        cToko.SimpanData();
        cToko.isiTable();
    }//GEN-LAST:event_jbSimpanActionPerformed

    private void jbUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUbahActionPerformed
        // TODO add your handling code here:
        cToko.Ubah();
        cToko.isiTable();
    }//GEN-LAST:event_jbUbahActionPerformed

    private void jbBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBersihkanActionPerformed
        // TODO add your handling code here:
        cToko.Reset();
    }//GEN-LAST:event_jbBersihkanActionPerformed

    private void jbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHapusActionPerformed
        // TODO add your handling code here:
        cToko.Hapus();
        cToko.isiTable();
    }//GEN-LAST:event_jbHapusActionPerformed

    private void jbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    private void tbBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBarangMouseClicked
        // TODO add your handling code here:
        int baris = tbBarang.getSelectedRow();
        
//        if(baris >= 0){
//            tfKode.setText(tbBarang.getValueAt(baris, 0).toString());
//            tfNama.setText(tbBarang.getValueAt(baris, 1).toString());
//            cbKategori.setSelectedItem(tbBarang.getValueAt(baris, 2).toString());
//            cbJenis.setSelectedItem(tbBarang.getValueAt(baris, 3).toString());
//            tfHarga.setText(tbBarang.getValueAt(baris, 4).toString());
//        }

        cToko.isiField(baris);
    }//GEN-LAST:event_tbBarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCari;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBersihkan;
    private javax.swing.JButton jbCari;
    private javax.swing.JButton jbHapus;
    private javax.swing.JButton jbKeluar;
    private javax.swing.JButton jbSimpan;
    private javax.swing.JButton jbUbah;
    private javax.swing.JTable tbBarang;
    private javax.swing.JTextField tfAdmin;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
    
    public JTextField getTxtKode(){         
        return tfKode;     
    }     
    public JTextField getTxtNama(){         
        return tfNama;     
    }     
    public JTextField getTxtHarga(){         
        return tfHarga;     
    }     
    public JComboBox getCbKategori(){         
        return cbKategori;     
    }     
    public JComboBox getCbJenis(){         
        return cbJenis;     
    }     
    public JComboBox getCbCariKategori(){         
        return cbCari;     
    }     
    public JButton getButtonHapus(){         
        return jbHapus;     
    }          
    public JButton getButtonBersih(){         
        return jbBersihkan;     
    }     
    public JButton getButtonSimpan(){         
        return jbSimpan;     
    }     
    public JButton getButtonUbah(){         
        return jbUbah;     
    }     
    public JButton getButtonKeluar(){         
        return jbKeluar;     
    }     
    public JTable getTableData(){         
        return tbBarang;     
    }
}

